/** Legacy stop requests resolve to the corresponding real implementation boundary. */
export const legacyPhaseTargets: Readonly<Record<string, string>> = {
  componentDetectionSolver: "escapeViaLocationSolver",
  netToPointPairsSolver: "escapeViaLocationSolver",
  componentTopologyGeneratorSolver: "highDensityRouteSolver",
  globalTopologyGeneratorSolver: "highDensityRouteSolver",
  nodeTargetMerger: "highDensityRouteSolver",
  singleLayerNodeMerger: "highDensityRouteSolver",
  strawSolver: "highDensityRouteSolver",
  deadEndSolver: "highDensityRouteSolver",
  multiSectionPortPointOptimizer: "highDensityRouteSolver",
  topologyPlanningSolver: "highDensityRouteSolver",
  topologyMergingSolver: "highDensityRouteSolver",
  nodeDimensionSubdivisionSolver: "highDensityRouteSolver",
  edgeSolver: "highDensityRouteSolver",
  availableSegmentPointSolver: "highDensityRouteSolver",
  necessaryCrampedPortPointSolver: "highDensityRouteSolver",
  preloadedTraceGraphSolver: "highDensityRouteSolver",
  portPointPathingSolver: "highDensityRouteSolver",
  uniformPortDistributionSolver: "highDensityRouteSolver",
  highDensityForceImproveSolver: "lengthMatchingPostProcessingSolver",
  highDensityRepairSolver: "lengthMatchingPostProcessingSolver",
  highDensityStitchSolver: "lengthMatchingPostProcessingSolver",
  mutatedPreloadedTraceSimplificationSolver: "lengthMatchingPostProcessingSolver",
  traceWidthSolver: "lengthMatchingPostProcessingSolver",
  globalDrcForceImproveSolver: "lengthMatchingPostProcessingSolver",
  pipeline9JointDrcRepairSolver: "lengthMatchingPostProcessingSolver",
  powerTraceExpansionSolver: "traceSimplificationSolver",
}
